#Competitive Threat and Market Share Loss Prediction

##Libraries

In [ ]:
# if kagglehub not found
!pip install --upgrade kagglehub

In [ ]:
import kagglehub
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
news_path = kagglehub.dataset_download("miguelaenlle/massive-stock-news-analysis-db-for-nlpbacktests")

print("Path to dataset files:", news_path)

Using Colab cache for faster access to the 'massive-stock-news-analysis-db-for-nlpbacktests' dataset.
Path to dataset files: /kaggle/input/massive-stock-news-analysis-db-for-nlpbacktests

In [ ]:
stock_path = kagglehub.dataset_download("ehallmar/daily-historical-stock-prices-1970-2018")

print("Path to dataset files:", stock_path)

Downloading to /root/.cache/kagglehub/datasets/ehallmar/daily-historical-stock-prices-1970-2018/1.archive...

100%|██████████| 469M/469M [00:04<00:00, 116MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/ehallmar/daily-historical-stock-prices-1970-2018/versions/1

##Dataset

In [ ]:
# news headlines
dataset_root = os.path.join(news_path, 'analyst_ratings_processed.csv')
news = pd.read_csv(dataset_root)
news

,Unnamed: 0,title,date,stock
0,0.0,Stocks That Hit 52-Week Highs On Friday,2020-06-05 10:30:00-04:00,A
1,1.0,Stocks That Hit 52-Week Highs On Wednesday,2020-06-03 10:45:00-04:00,A
2,2.0,71 Biggest Movers From Friday,2020-05-26 04:30:00-04:00,A
3,3.0,46 Stocks Moving In Friday's Mid-Day Session,2020-05-22 12:45:00-04:00,A
4,4.0,B of A Securities Maintains Neutral on Agilent...,2020-05-22 11:38:00-04:00,A
...,...,...,...,...
1400464,1413844.0,Top Narrow Based Indexes For August 29,2011-08-29 10:41:00-04:00,ZX
1400465,1413845.0,Recap: Wednesday's Top Percentage Gainers and ...,2011-06-22 16:44:00-04:00,ZX
1400466,1413846.0,UPDATE: Oppenheimer Color on China Zenix Auto ...,2011-06-21 08:26:00-04:00,ZX
1400467,1413847.0,Oppenheimer Initiates China Zenix At Outperfor...,2011-06-21 05:59:00-04:00,ZX
1400468,1413848.0,China Zenix Auto International Opens For Tradi...,2011-05-12 09:36:00-04:00,ZX

In [ ]:
# historic stock prices
dataset_root = os.path.join(stock_path, 'historical_stock_prices.csv')
stock = pd.read_csv(dataset_root)
stock

         ticker   open  close  adj_close    low   high   volume        date
0           AHH  11.50  11.58   8.493155  11.25  11.68  4633900  2013-05-08
1           AHH  11.66  11.55   8.471151  11.50  11.66   275800  2013-05-09
2           AHH  11.55  11.60   8.507822  11.50  11.60   277100  2013-05-10
3           AHH  11.63  11.65   8.544494  11.55  11.65   147400  2013-05-13
4           AHH  11.60  11.53   8.456484  11.50  11.60   184100  2013-05-14
...         ...    ...    ...        ...    ...    ...      ...         ...
20973884    NZF  14.60  14.59  14.590000  14.58  14.62   137500  2018-08-20
20973885    NZF  14.60  14.58  14.580000  14.57  14.61   151200  2018-08-21
20973886    NZF  14.58  14.59  14.590000  14.57  14.63   185400  2018-08-22
20973887    NZF  14.60  14.57  14.570000  14.57  14.64   135600  2018-08-23
20973888    NZF  14.60  14.69  14.690000  14.59  14.69   180900  2018-08-24

[20973889 rows x 8 columns]

###Data Cleaning

In [ ]:
# remove "unnameed: 0" column from news_df, duplicates as the index

In [ ]:
# reuncate "date" info to contain only YYYY-MM-DD from news_df, so take out the time

In [ ]:
# remove any rows with null values from news_df

In [ ]:
# remove any rows from news_df where the date exceeds date range of stock_df

In [ ]:
# remove rows from news_df where value in "stock" does not match "ticker" value in stock_df

In [ ]:
# remove any rows with null values from stock_df

In [ ]:
# remove any rows from stock_df where the date exceeds the date range of news_df

In [ ]:
# remove rows from stock_df where value in "ticker" value does not match "stock" value in news_df

In [ ]:
# by matching the dates of news_df to dates of stock_df,
# only keep rows stock_df with dates 3 days from the news headline publish date and also the row for the date after
## ex. news_date(2025-04-23); keep rows from stock_df with dates {2025-04-21,2025-04-22, 2025-04-23, 2025-04-24}

In [ ]:
# by matching the date of the news headline and the stock ticker,
# add the prices of the stock from the past 3 days to a new column in news_df
# also add the next day's stock price to the news_df as a new column

In [ ]:
# add column in news_df for whether stock prices went up or down
## ex. price from 1_day_ago is higher than price of next_day -> price_went_up column value = 1
## ex. price from 1_day_ago is lower than price of next_day -> price_went_up column value = 0

##Visualizations

In [ ]:
# plot the top # most mentioned stock ticker in news_df

In [ ]:
# plot the top # most traded stocks in stock_df

In [ ]:
# plot the top # stocks with the largest price changes within a day

In [ ]:
# plot counts of top bigrams (n-grams)

In [ ]:
# plot price_went_up column

In [ ]:
# other plots you deem fit

##Data Spliting

In [ ]:
X = news.drop('price_went_up', axis=1)
y = news['price_went_up']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=6, stratify=True)

##Pre-processing